version: "3.9"

services:
  optimir_api:
    build: ./backend
    container_name: optimir_api
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/chroma_db:/app/chroma_db
      - ./backend/app:/app/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://optimir_api:8000
    depends_on:
      - optimir_api
